### PR TITLE
Removed default `subscribable=true` value

### PR DESCRIPTION
**Pull request by ricardbejarano**
This solves #11.

### CODE REVIEW

**Comment by ricardbejarano** [comment]
Is there intention to fix this? It's been open for 3 weeks now.

**Comment by gyfis** [comment]
@ricardbejarano Hi, thanks a lot for the PR! Yes, we'll merge this soon and release a new version (along with the request headers addition to monitors). Sorry for the delay!

**Comment by adikus** [comment]
Thanks! @ricardbejarano

**Comment by ricardbejarano** [comment]
Cool. Thank you!

**Pull request merged**
